name: training_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.20.1

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  sqflite: ^2.0.2+1
  flutter_picker: ^2.0.3
  smart_select: ^4.3.2
  overlay_support: ^1.2.1
  direct_select: ^2.0.0
  sticky_headers: ^0.2.0
  flutter_native_splash: ^2.1.6
  table_calendar: ^3.0.5
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
    - assets/images/

  fonts:
    - family: NotoSerifJP
      fonts:
        - asset: assets/fonts/NotoSerifJP-Regular.otf
